#!/bin/bash
set -e

. /usr/share/debconf/confmodule  # Load Debconf functions

db_input critical jump-start-website/install-dir || true
db_input critical jump-start-website/owner || true
db_input critical jump-start-website/install-ruby || true
db_input high jump-start-website/db-name || true
db_input high jump-start-website/db-user || true
db_input critical jump-start-website/db-password || true
db_go
