#!/bin/bash
set -e

. /usr/share/debconf/confmodule  # Load Debconf functions

db_input high jump-start-server/db-name || true
db_input high jump-start-server/db-user || true
db_input critical jump-start-server/db-password || true
db_go
