#!/bin/bash

# postinst script for Jump Start Server

set -e  # Exit on error

. /usr/share/debconf/confmodule

db_get jump-start-website/install-dir
INSTALL_DIRECTORY="$RET"

db_get jump-start-website/owner
OWNER="$RET"

db_get jump-start-website/install-ruby
INSTALL_RUBY="$RET"

db_get jump-start-website/db-name
DB_NAME="$RET"

db_get jump-start-website/db-user
DB_USERNAME="$RET"

db_get jump-start-website/db-password
export DB_PASSWORD="$RET"

if [ -z "${INSTALL_DIRECTORY}" ]; then
  echo "Please enter an install directory." >&2
  exit 1
fi

if [ -z "${OWNER}" ]; then
  echo "Please specify an owner for the Rails code." >&2
  exit 1
fi

if [ -z "${INSTALL_RUBY}" ]; then
  echo "Please specify if ruby is to be installed." >&2
  exit 1
fi

if [ -z "${DB_NAME}" ]; then
  echo "Please enter a database name." >&2
  exit 1
fi

if [ -z "${DB_USERNAME}" ]; then
  echo "Please enter a username for the database user." >&2
  exit 1
fi

if [ -z "${DB_PASSWORD}" ]; then
  echo "Please enter a password for the database user." >&2
  exit 1
fi

if [ "$INSTALL_RUBY" = "true" ]; then
  apt update && apt install -y curl build-essential libssl-dev libreadline-dev zlib1g-dev

  if ! command -v ruby-install >/dev/null; then
      curl -L https://github.com/postmodern/ruby-install/archive/refs/tags/v0.9.1.tar.gz | tar -xz
      cd ruby-install-0.9.1
      make install
      cd ..
      rm -rf ruby-install-0.9.1
  fi

  sudo -u "$OWNER" ruby-install ruby 3.2

  echo 'export PATH="$HOME/.rubies/ruby-3.2.*/bin:$PATH"' | sudo -u "$OWNER" tee -a ~"$OWNER"/.bashrc > /dev/null
fi

if ! command -v ruby >/dev/null 2>&1 || ! ruby -v | grep -q " 3.2."; then
  echo "Ruby 3.2.* could not be found." >&2
  exit 1
fi

if [ ! -d "${INSTALL_DIRECTORY}" ]; then
  mkdir -p "${INSTALL_DIRECTORY}"
fi

TMP_DIR=$(dpkg-query -L jump-start-website | grep -E '^/usr/share/' | head -n 1)
cp -r "${TMP_DIR}/"* "${INSTALL_DIRECTORY}" || { echo "Failed to copy files from directory ${TMP_DIR} to '${INSTALL_DIRECTORY}'." >&2; exit 1; }
chown -R "${OWNER}:${OWNER}" "${INSTALL_DIRECTORY}" || { echo "Failed to change owner to ${OWNER} for ${INSTALL_DIRECTORY}'." >&2; exit 1; }
rm -rf "${TMP_DIR}" || true
cd "${INSTALL_DIRECTORY}" || { echo "Failed to change directory '${INSTALL_DIRECTORY}'." >&2; exit 1; }
su "$OWNER" -c "bin/setup_ruby.rb $DB_NAME $DB_USERNAME $DB_PASSWORD"
echo "Jump Start Server configured successfully."
exit 0
