#!/bin/sh
set -e

install_dir=`dpkg-query -L jump-start-website | grep -E '^/usr/share/' | head -n 1`
tmp_dir=""${install_dir}/tmp"

case "$1" in
    remove)
        echo "Removing package files..."
        rm -rf "${tmp_dir}"
        ;;
    purge)
        echo "Purging package completely..."
        rm -rf "${tmp_dir}"
        ;;
esac

exit 0
