#!/bin/bash

#postinst

set -e

. /usr/share/debconf/confmodule

# Retrieve database values properly
db_get jump-start-server/db-name
DB_NAME="$RET"

db_get jump-start-server/db-user
DB_USERNAME="$RET"

db_get jump-start-server/db-password
export DB_PASSWORD="$RET"

if [ ! -d "/opt/jump-start-server" ]; then
  echo "Error: directory /opt/jump-start-server doesn't exist. Exiting..." >&2
  exit 1
fi

cd /opt/jump-start-server/ || { echo "Failed to change directory." >&2; exit 2; }

ruby bin/setup.rb "$DB_NAME" "$DB_USERNAME"

# Install Bundler
echo "Installing bundler..."
gem install bundler -v '~> 2.5' || { echo "Failed to install bundler." >&2; exit 3; }
echo "Bundler installed."

# Install Gems
echo "Installing gems with Bundler..."
bundle install || { echo "Failed to install gems." >&2; exit 4; }
echo "Gems installed."

# Run Database Migrations
echo "Running database migrations..."
bundle exec rails db:migrate || { echo "Failed to migrate the database." >&2; exit 5; }
echo "Database migrations completed."

# Precompile Assets (for Production)
if [ "${RAILS_ENV}" = "production" ]; then
    echo "Precompiling assets for production..."
    bundle exec rails assets:precompile || { echo "Failed to precompile assets." >&2; exit 6; }
    echo "Assets precompiled."
fi

echo "Jump Start Server configured."
exit 0
